version: "3.8"

services:
    db:
        image: mysql:8.3
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql # Persistent data volume
            - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d # Initialization scripts
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8080:8080"
        env_file:
            - .env
    dashboard:
        build:
            context: ./dashboard
            dockerfile: Dockerfile
        depends_on:
            - backend
        ports:
            - "3000:3000" # Map port 80 inside the container to port 80 on the host

volumes:
    db_data:
