version: "3.8"

services:
    db:
        image: mysql:8.3
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql # Persistent data volume
            - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d # Initialization scripts
        restart: always # Ensure the DB always restarts on failure
        networks:
            - backend_network # Connect DB to the backend network

    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8080:8080"
        env_file:
            - .env
        networks:
            - backend_network # Backend and DB on the same network
            - dashboard_network # Optional: If your dashboard needs direct access to backend via internal network

    dashboard:
        build:
            context: ./dashboard
            dockerfile: Dockerfile
        depends_on:
            - backend
        ports:
            - "3000:3000"
        networks:
            - dashboard_network # Connect dashboard to its own network

networks:
    backend_network: # Defines a network for the backend and DB
    dashboard_network: # Defines a network for the dashboard

volumes:
    db_data:
