/*
-- Query: SELECT * FROM test_data.accounting_name
LIMIT 0, 1000

-- Date: 2024-02-11 21:02
*/
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (125,'5555','ใช้สอยวัสดุ','55');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (126,'111111','เงินสด','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (127,'111201','เงินฝากกระแสรายวัน ธ.ไทยพาณิชย์-ปกส.','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (128,'111202','เงินฝากกระแสรายวัน ธ.ไทยพาณิชย์ - ไฟฟ้า','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (129,'111203','เงินฝากกระแสรายวัน ธ.ไทยพาณิชย์ - ส่งออก 7923','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (130,'111221','เงินฝากออมทรัพย์ ธ.ไทยพาณิชย์ SCB - ประโยชน์ ','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (131,'111222','เงินฝากออมทรัพย์ ธ.ไทยพาณิชย์ 792-203206-9','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (132,'111223','เงินฝากออมทรัพย์ ธ.ไทยพาณิชย์ - FCD 792592201','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (133,'111224','เงินฝากออมทรัพย์ ธ.ไทยพาณิชย์ - Forword 79210','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (134,'111321','เงินฝากออมทรัพย์ ธ.กสิกร 1672502086','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (135,'111322','เงินฝากออมทรัพย์ ธ.กสิกร 1672341139','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (136,'111421','เงินฝากกระแสรายวัน ธ.กรุงเทพ - ส่งออก 2733020','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (137,'111422','เงินฝากออมทรัพย์ ธ.กรุงเทพฯ 2734552637','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (138,'111423','เงินฝากออมทรัพย์ ธ.กรุงเทพ 2734533496','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (139,'111501','เงินฝากกระแสรายวัน ธ.กรุงไทย - คุณประโยชน์','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (140,'111502','เงินฝากกระแสรายวัน ธ.กรุงไทย 4226011465','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (141,'111521','เงินฝากออมทรัพย์ ธ.กรุงไทย 4220374396','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (142,'111522','เงินฝากออมทรัพย์ ธ.กรุงไทย 4220382887','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (143,'111601','เงินฝากกระแสรายวัน ธ.ทหารไทย 3371050455','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (144,'111721','เงินฝากออมทรัพย์ ธ.ธกส 8062599655','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (145,'111722','เงินฝากออมทรัพย์ ธ.ธกส 8062697817','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (146,'111723','เงินฝากออมทรัพย์ ธ.ธกส 8062565898','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (147,'112111','ลูกหนี้การค้า','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (148,'113111','เงินให้กู้ยืมระยะสั้นแก่บุคคลที่เกี่ยวข้อง','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (149,'113211','เงินให้กู้ยืมระยะสั้นแก่บุคคลอื่น','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (150,'114111','สินค้าคงเหลือ','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (151,'114121','วัตถุดิบคงเหลือ','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (152,'114131','งานระหว่างทำ','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (153,'115111','ภาษีซื้อ','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (154,'115121','ภาษีถูกหัก ณ ที่จ่าย','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (155,'115131','ภาษีเงินได้จ่ายล่วงหน้า','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (156,'115141','ค่าใช้จ่ายจ่ายล่วงหน้า','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (157,'115151','อะไหล่รอการเบิกจ่าย','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (158,'115161','ค่าใช้จ่ายรอตัดจ่าย','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (159,'121111','ที่ดิน','04');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (160,'121211','โรงงาน','04');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (161,'121211.1','ค่าเสื่อมสะสม - โรงงาน','15');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (162,'121311','อาคาร','04');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (163,'121311.1','ค่าเสื่อมสะสม - อาคาร','15');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (164,'121411','เครื่องมือเครื่องจักรและอุปกรณ์','04');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (165,'121411.1','ค่าเสื่อมสะสม - เครื่องมือเครื่องจักรและอุปกร','15');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (166,'121511','เครื่องตกแต่งและอุปกรณ์สำนักงาน','04');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (167,'121511.1','ค่าเสื่อมสะสม - เครื่องตกแต่งและอุปกรณ์สำนักง','15');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (168,'121611','ยานพาหนะ','04');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (169,'121611.1','ค่าเสื่อมสะสม - ยานพาหนะ','15');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (170,'121711','สินทรัพย์อื่น','04');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (171,'121711.1','ค่าเสื่อมสะสม - สินทรัพย์อื่น','15');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (172,'122111','งานระหว่างก่อสร้าง','04');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (173,'123111','เงินประกัน','04');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (174,'123211','เงินให้กู้ยืมยาว','04');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (175,'211201','เงินเบิกเกินบัญชี ธ.ไทยพาณิชย์ 7923000181','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (176,'211301','เงินเบิกเกินบัญชี ธ.กสิกรไทย 1671015831','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (177,'211401','เงินเบิกเกินบัญชี ธ.กรุงเทพ 2733020065','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (178,'221111','เจ้าหนี้การค้า','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (179,'221112','เช็คสั่งจ่ายล่วงหน้า','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (180,'221311','ค่าใช้จ่ายค้างจ่าย','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (181,'221411','เงินกู้ยืมระยะสั้นจากบุคคลที่เกี่ยวข้อง','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (182,'221511','เงินกู้ยืมระยะสั้นจากบุคคลอื่น','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (183,'221611','ภาษีขาย','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (184,'221612','ภาษีมูลค่าเพิ่มค้างจ่าย','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (185,'221613','ภาษีหัก ณ ที่จ่ายค้างจ่าย','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (186,'221614','ภาษีเงินได้ค้างจ่าย','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (187,'223111','เงินกู้ยืมระยะยาวจากบุคคลที่เกี่ยวข้อง','06');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (188,'223121','เงินกู้ยืมระยะยาวจากบุคคลอื่น','06');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (189,'311111','ทุนเรือนหุ้น','08');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (190,'311121','กำไร - ขาดทุน สะสมยังไม่ได้แบ่ง','08');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (191,'411111','รายได้จากการขาย - ข้าวสาร','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (192,'411111.1','รายการปรับปรุงจากตัดตั๋ว - ข้าวสาร','18');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (193,'411111.2','รับคืน - ข้าวสาร','18');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (194,'411112','รายได้จากการขาย - รำอ่อน','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (195,'411112.1','รายการปรับปรุงจากการตัดตั๋ว - รำอ่อน','18');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (196,'411113','รายได้จากการขาย - รำหยาบ','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (197,'411113.1','รายการปรับปรุงจากการตัดตั๋ว - รำหยาบ','18');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (198,'411114','รายได้จากการขาย - แกลบ','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (199,'411114.1','รายการปรับปรุงจากการตัดตั๋ว - แกลบ','18');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (200,'411115','รายได้จากการขาย - ข้าวเปลือก','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (201,'411115.1','รายการปรับปรุงจากการตัดตั๋ว - ข้าวเปลือก','18');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (202,'411121','รายได้ค่าเช่าคลัง','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (203,'411131','รายได้ค่าฝากเก็บ','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (204,'411141','กำไร - ขาดทุน จากอัตราการแลกเปลี่ยน','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (205,'411151','กำไร - ขาดทุน จากการจำหน่ายทรัพย์สิน','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (206,'411161','รายได้จากการขายขี้เถ้า','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (207,'411171','รายได้ดอกเบี้ยรับ','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (208,'411191','ผลจากการปรับตัวเลขทางบัญชี','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (209,'511111','ซื้อวัตถุดิบ','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (210,'511111.1','ส่วนลดจ่าย','19');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (211,'511111.2','ส่งคืนวัตถุดิบ','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (212,'521111','เงินเดือน - ฝ่ายผลิต','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (213,'521112','ค่าจ้างแรงงาน','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (214,'521113','ค่าไฟฟ้า-ฝ่ายผลิต','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (215,'521114','ค่าน้ำมันเชื้อเพลิง','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (216,'521115','ค่าน้ำประปา-ฝ่ายผลิต','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (217,'521116','ค่าตรวจสอบคุณภาพข้าว','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (218,'521117','ค่าน้ำยาเคมีและสีย้อม','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (219,'521118','ค่าบรรจุภัณฑ์','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (220,'521119','ค่าบำรุงรักษาเครื่องมือเครื่องจักร','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (221,'521120','ค่าวัสดุสิ้นเปลือง','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (222,'521211','ค่าเสื่อมราคา - โรงงาน','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (223,'521212','ค่าเสื่อมราคา - เครื่องมือเครื่องจักร','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (224,'531111','ต้นทุนสินค้าที่ขาย','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (292,'411116','ส่วนลดรับ','18');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (226,'531111.2','ส่งคืนสินค้า','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (227,'541111','ค่านายหน้า','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (281,'541113','ค่าแรงงาน','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (229,'551111','ค่าใช้จ่ายในการดำเนินงาน/บริหาร','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (230,'551112','เงินเดือน - บริหาร','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (231,'551113','เงินเดือน - ดำเนินงาน','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (232,'551114','เงินโบนัส','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (233,'551115','ค่าไฟฟ้า-ดำเนินงาน','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (234,'551116','ค่าน้ำประปา-ดำเนินงาน','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (235,'551117','ค่าโทรศัพท์','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (236,'551118','ค่าเครื่องเขียนแบบพิมพ์','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (237,'551119','ค่าเบี้ยประกันภัยจ่าย','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (276,'221313','เจ้าหนี้ค่าขนส่ง','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (239,'551121','ค่าภาษีเงินได้ตามประมวลรัษฎากร','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (240,'551122','ค่าภาษีอากรอื่น','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (241,'551123','เงินทดแทน/สมทบประกันสังคม','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (242,'551124','ค่าจัดทำบัญชี','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (243,'551125','ค่าสอบบัญชี','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (244,'551126','ค่าธรรมเนียม','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (245,'551127','ค่าธรรมเนียม - อคส.','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (246,'551128','เงินบริจาค','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (247,'551129','ค่าใช้จ่ายเบ็ดเตล็ด','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (248,'551211','ค่าเสื่อมราคา - อาคาร','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (249,'551212','ค่าเสื่อมราคา - เครื่องตกแต่งและอุปกรณ์','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (250,'551213','ค่าเสื่อมราคา - ยานพาหนะ','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (251,'551411','เงินบริจาคการศึกษา','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (252,'551412','ค่าเบี้ยประกันชีวิต','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (253,'551413','ค่าบัตรเครดิต/ค่าโทรศัพท์','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (254,'551414','ค่าใช้จ่ายครัวเรือน','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (255,'599999','ภาษีเงินได้','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (263,'115142','ค่าซื้อวัตถุดิบ จ่ายล่วงหน้า','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (256,'114122','ค่าขนส่งวัตถุดิบขาเข้า','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (257,'115143','ค่าขนส่งเบิกล่วงหน้า','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (258,'411110','รายได้จากการขาย - ข้าวส่งออก','09');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (259,'411111.3','ค่าขาดน้ำหนัก','18');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (260,'411111.4','ค่ากระสอบ','18');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (261,'411181','รายได้อื่น','10');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (264,'112112','เช็ครับล่วงหน้า','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (265,'531112','คชจวัสดุ/ค่าซ่อมงานการผลิต-บรรจุ','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (266,'531113','คชจวัสดุ/ค่าซ่อมเครื่องจักรย่อยฝ่ายผลิต','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (267,'531114','คชจ.น้ำยาหล่อลื่นยานยนต์ฝ่ายผลิต','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (268,'531115','คชจ.วัสดุ/ค่าซ่อมโครงสร้างและสิ่งปลูกสร้าง','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (269,'531116','คชจ.วัสดุสิ้นเปลือง','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (280,'551120','ค่าน้ำมันเชื้อเพลิง-ดำเนินงาน','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (271,'531118','ค่ารมยา','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (273,'541112','คชจวัสดุ/ค่าซ่อมเครื่องจักร-อุปกรณ์ฝ่ายบริหาร','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (274,'541114','วัสดุสำนักงาน','11');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (275,'531120','ค่าบรรจุภัณฑ์','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (277,'531119','ค่าระวาง ขนส่ง','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (283,'112113','ภาษีหัก ณ ที่จ่ายรอเรียกคืน','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (284,'112114','ค่าใช้จ่ายจ่ายล่วงหน้า-ข้าวสาร','01');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (285,'511112','ซื้อสินค้า','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (286,'112115','ภาษีหักณ ที่จ่าย-จ่ายแทน','04');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (287,'112116','ค่าขนส่ง-จ่ายแทน','04');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (288,'531121','คชจ. Retro Bonus 1%','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (289,'531122','คชจ.B2B-Ecommerce 0.5%','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (290,'531123','คชจ.Logistic service 4.1%','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (291,'221611.1','ภาษีขายรอใช้สิทธิ์','05');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (293,'531124','ค่าสารเคมี-แม็คโคร','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (294,'531125','คชจ.ปรับ Late Penalty','12');
INSERT INTO `accounting_name` (`id`,`accounting_id`,`accounting_name`,`accounting_type`) VALUES (295,'111801','เงินฝากออมทรัพย์ PB ธนาคารกสิกรไทย 0501630713','01');

